server:
  port: 10000

datasource:
  host: 127.0.0.1
  port: 3306
  username: root
  password: root
  db_name: sky-take-out

redis:
  host: 127.0.0.1
  port: 6379
  password:
  data_base: 1

log:
  level: info

jwt:
  admin:
    # 设置jwt签名加密时使用的秘钥
    secret: admin
    # 设置jwt过期时间
    ttl: 7200000
    # 设置前端传递过来的令牌名称
    name: token
  user:
    # 设置jwt签名加密时使用的秘钥
    secret: user
    # 设置jwt过期时间
    ttl: 7200000
    # 设置前端传递过来的令牌名称
    name: Authorization


alioss:
  endpoint: You Option
  access_key_id: You Option
  access_key_secret: You Option
  bucket_name: You Option

wechat:
  appid: You Option
  secret: You Option